//created on: 2017-04-09
package rules

//list any import classes here.

import com.RuleEngine.model.sm_nodes

//declare any global variables here

//global FactFromDatabase fact;

rule "Test"

    when
        sm_nodes(id == 1)
    then
        System.out.println("-------- Udalo Sie --------");
end

rule "Test2"

    when
        sm_nodes()
    then
        System.out.println("--------- sm_nodes() -----------");
end